import { spawnSync } from 'node:child_process';
import { cpSync, mkdirSync, mkdtempSync, readFileSync, rmSync, symlinkSync, writeFileSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { dirname, join, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import { afterAll, describe, expect, it } from 'vitest';

/**
 * `scripts/gen-examples.mjs` generates the site payload and the doc blocks.
 *
 * Three things it owns, and each fails differently:
 *
 *  - `site/assets/data.js`, compared byte-for-byte under `--check`;
 *  - the `<!-- example: … -->` **fenced content** in `docs/targets/*.md`,
 *    rewritten from the real export on every non-check run;
 *  - the `<!-- fields: … -->` **tables** in the same files, rendered from
 *    `format-spec.mjs`.
 *
 * The third is the one with no `--check` path at all, which the gate's own
 * comment does not say and this file asserts: a stale field table is only ever
 * corrected by a *writer* run, so a repository whose tables drifted fails
 * nothing. That is `audit.md`'s P2-4 and it is recorded here rather than
 * inferred.
 *
 * The gate is run as a subprocess against a copy in a throwaway tree. Its
 * `docs/targets/` directory is built by the fixture rather than copied from the
 * repository, because the tests below are about the **rewrite rules** -- which
 * marker matches which file, and what happens when one does not -- and a
 * fixture made of the real seven documents would make each assertion depend on
 * how those documents happen to be written today.
 */

const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), '..', '..', '..');
const SCRIPT = 'gen-examples.mjs';
const REAL_EXAMPLES = resolve(ROOT, 'examples/order-prod');

interface Outcome {
  status: number;
  stdout: string;
  stderr: string;
}

const scratch = mkdtempSync(join(tmpdir(), 'rca-bench-genex-'));
afterAll(() => rmSync(scratch, { recursive: true, force: true }));

let counter = 0;

/**
 * A throwaway tree holding the gate, the real example directory, the real
 * `format-spec.mjs`, and a `docs/targets/` the caller writes.
 *
 * `format-spec.mjs` is copied because the gate imports it *by relative path*
 * from its own directory; `packages/` and `node_modules/` are linked so the
 * gate loads the shipped build (`zod` included) rather than a stub.
 */
function treeWith(docs: Record<string, string> = {}): string {
  counter += 1;
  const tree = join(scratch, `tree-${counter}`);
  mkdirSync(join(tree, 'scripts'), { recursive: true });
  mkdirSync(join(tree, 'site', 'assets'), { recursive: true });
  mkdirSync(join(tree, 'docs', 'targets'), { recursive: true });
  writeFileSync(join(tree, 'scripts', SCRIPT), readFileSync(resolve(ROOT, 'scripts', SCRIPT), 'utf8'));
  writeFileSync(
    join(tree, 'scripts', 'format-spec.mjs'),
    readFileSync(resolve(ROOT, 'scripts', 'format-spec.mjs'), 'utf8'),
  );
  cpSync(REAL_EXAMPLES, join(tree, 'examples', 'order-prod'), { recursive: true });
  symlinkSync(resolve(ROOT, 'packages'), join(tree, 'packages'), 'dir');
  symlinkSync(resolve(ROOT, 'node_modules'), join(tree, 'node_modules'), 'dir');
  for (const [name, body] of Object.entries(docs)) writeFileSync(join(tree, 'docs', 'targets', name), body);
  return tree;
}

function run(tree: string, args: string[] = []): Outcome {
  const result = spawnSync(process.execPath, [join(tree, 'scripts', SCRIPT), ...args], {
    encoding: 'utf8',
    cwd: tree,
  });
  if (result.error !== undefined) {
    return { status: -1, stdout: result.stdout ?? '', stderr: result.error.message };
  }
  return { status: result.status ?? -1, stdout: result.stdout ?? '', stderr: result.stderr ?? '' };
}

/** An example marker the gate will rewrite, for a file the exporters really emit. */
function exampleMarker(): string {
  return [
    '# openrca-1.0',
    '',
    '<!-- example: openrca-1.0/order-prod/query.csv -->',
    '```csv',
    'STALE,CONTENT,FROM,A,PREVIOUS,RUN',
    '```',
    '',
  ].join('\n');
}

describe('scripts/gen-examples.mjs · the payload it generates', () => {
  it('writes a data file that assigns the global the site reads', () => {
    // The precondition. The site is a dependency-free static app, so the
    // payload has to be a plain script assigning `window.RBF_DATA` -- not a
    // module, not JSON. A gate that produced ESM would pass every negative
    // below and leave the site blank.
    const tree = treeWith();
    const result = run(tree);

    expect(result.status).toBe(0);
    const data = readFileSync(join(tree, 'site', 'assets', 'data.js'), 'utf8');
    expect(data.startsWith('/* Generated by scripts/gen-examples.mjs - do not edit by hand. */')).toBe(true);
    expect(data).toContain('window.RBF_DATA = {');
    expect(data).toContain('"generatedBy": "scripts/gen-examples.mjs"');
  });

  it('covers every target the scorer declares, each with its own report', () => {
    // The payload is the site's data source. A target missing from it is a
    // format a visitor cannot inspect, and the loss would be invisible --
    // `data.js` is a valid file with one fewer key.
    const tree = treeWith();
    expect(run(tree).status).toBe(0);
    const data = readFileSync(join(tree, 'site', 'assets', 'data.js'), 'utf8');
    const payload = JSON.parse(
      data.slice(data.indexOf('window.RBF_DATA = ') + 'window.RBF_DATA = '.length).replace(/;\n$/, ''),
    ) as {
      targets: Record<string, { report: unknown; files: Record<string, string>; skipped?: unknown }>;
    };

    // Nine targets: OpenRCA 1.0/2.0, the three RCAEval suites as separate
    // targets, RCA100, AIOps2025, Cloud-OpsBench and ITBench.
    expect(Object.keys(payload.targets).sort()).toEqual([
      'aiops2025',
      'cloud-opsbench',
      'itbench',
      'openrca-1.0',
      'openrca-2.0',
      'rca100',
      'rcaeval-re1',
      'rcaeval-re2',
      'rcaeval-re3',
    ]);
    // `rcaeval-re3` is the one target that admits code-level faults only, and
    // the shipped example is a CPU-saturation case -- so its export is
    // **empty by contract**, which `check-official.mjs` also reports as its one
    // `SKIP`. The first version of this loop asserted a non-empty export for
    // all nine and failed here; the assertion below is the corrected one, and
    // the empty export is asserted as *expected* rather than tolerated.
    for (const [key, target] of Object.entries(payload.targets)) {
      expect(target.report, key).toBeTypeOf('object');
      if (key === 'rcaeval-re3') {
        expect(Object.keys(target.files).length, key).toBe(0);
        expect(target.skipped, `${key} must say why it is empty`).toBeTypeOf('object');
        continue;
      }
      // Every other target carries a real export: a target whose `files` were
      // empty would still serialise and would make the site show a format with
      // no fields.
      expect(Object.keys(target.files).length, key).toBeGreaterThan(0);
    }
  });

  it('passes --check against the file it has just written', () => {
    // The other half of the contrast for the staleness case below.
    const tree = treeWith();
    expect(run(tree).status).toBe(0);

    const result = run(tree, ['--check']);

    expect(result.status).toBe(0);
    expect(result.stdout).toContain('examples data is up to date');
  });

  it('refuses a stale data file and names the command that fixes it', () => {
    // The guarantee that makes the committed payload meaningful. The diagnostic
    // has to carry the repair, because "is stale" alone does not say which
    // direction the drift went.
    const tree = treeWith();
    expect(run(tree).status).toBe(0);
    writeFileSync(join(tree, 'site', 'assets', 'data.js'), 'window.RBF_DATA = {"stale": true};\n');

    const result = run(tree, ['--check']);

    expect(result.status).toBe(1);
    expect(result.stderr).toContain('data.js is stale');
    expect(result.stderr).toContain('pnpm examples:gen');
  });

  it('refuses --check when the data file does not exist at all', () => {
    // A separate exit with a separate sentence: a missing file is not a stale
    // one, and the operator's first action differs (`gen` versus `investigate`).
    const tree = treeWith();

    const result = run(tree, ['--check']);

    expect(result.status).toBe(1);
    expect(result.stderr).toContain('is missing');
    expect(result.stderr).toContain('pnpm examples:gen');
  });
});

describe('scripts/gen-examples.mjs · the doc blocks it rewrites', () => {
  it('replaces a stale example block with the real export', () => {
    // The doc-block half of the generator. The replacement is what makes a
    // documented sample unable to drift from the code that produces it, so an
    // unchanged file after a writer run is the defect.
    const tree = treeWith({ 'openrca-1.0.md': exampleMarker() });
    const result = run(tree);

    expect(result.status).toBe(0);
    expect(result.stdout).toContain('openrca-1.0.md');

    const after = readFileSync(join(tree, 'docs', 'targets', 'openrca-1.0.md'), 'utf8');
    expect(after).not.toContain('STALE,CONTENT,FROM,A,PREVIOUS,RUN');
    expect(after).toContain('instruction_id,query,occurrence_datetime');
    // The marker survives the rewrite, so a second run is idempotent rather
    // than consuming the block it just filled.
    expect(after).toContain('<!-- example: openrca-1.0/order-prod/query.csv -->');
  });

  it('is idempotent: a second run changes nothing', () => {
    // Not decoration. If the rewrite were not fixed-point, every run would
    // produce a diff and the committed file would be stale the moment anyone
    // ran the generator twice.
    const tree = treeWith({ 'openrca-1.0.md': exampleMarker() });
    expect(run(tree).status).toBe(0);
    const first = readFileSync(join(tree, 'docs', 'targets', 'openrca-1.0.md'), 'utf8');

    expect(run(tree).status).toBe(0);
    const second = readFileSync(join(tree, 'docs', 'targets', 'openrca-1.0.md'), 'utf8');

    expect(second).toBe(first);
  });

  it('honours the truncate modifier rather than writing the whole export', () => {
    // `truncate=N` keeps the first N lines and appends a count of the rest.
    // A gate that ignored the modifier would write a full metrics table into
    // the docs -- correct content, unusable page.
    //
    // Two earlier versions of this test failed, and both were measuring the
    // wrong thing rather than the modifier:
    //
    //  - `order-prod/metrics.csv` is **not a path this exporter emits**.
    //    OpenRCA writes metrics into `{date}/telemetry/metric/…`, so the run
    //    threw `example path '…' not exported` and the assertion on the
    //    truncation suffix could not be reached.
    //  - `order-prod/record.csv` *is* a real path but has three lines
    //    (header plus one row), so `truncate=2` had nothing to cut and no
    //    `… N more lines` marker was emitted. The test then asserted the full
    //    text was absent and found it present -- correctly, because with two
    //    lines kept out of three the kept portion still contains the row.
    //
    // The file used now has seventeen lines, which is what makes the modifier
    // observable at all. A truncation test needs a subject long enough to
    // truncate; that is the whole lesson of the two failures above.
    const marker = [
      '# openrca-1.0',
      '',
      '<!-- example: openrca-1.0/order-prod/2026_09_06/telemetry/metric/case-001.csv truncate=2 -->',
      '```csv',
      'stale',
      '```',
      '',
    ].join('\n');
    const tree = treeWith({ 'openrca-1.0.md': marker });
    expect(run(tree).status).toBe(0);

    const after = readFileSync(join(tree, 'docs', 'targets', 'openrca-1.0.md'), 'utf8');
    // The modifier is preserved so the next run truncates identically.
    expect(after).toContain('truncate=2');
    // The suffix names how much was dropped, so a reader can tell a short
    // table from a table that was cut.
    expect(after).toMatch(/… 1[0-9] more lines/);
    // The three columns of the full metrics file do not all appear: what is
    // written is a prefix, not the export.
    const block = after.slice(after.indexOf('```csv'), after.lastIndexOf('```'));
    expect(block.split('\n').filter((line) => line.includes('2026-09-06'))).toHaveLength(1);
  });

  it('refuses an example that names a target the exporters do not produce', () => {
    // The throw the gate has and no test ever entered. A marker referencing a
    // target that was renamed or removed is a documentation bug that must stop
    // the generator -- silently skipping it would leave a stale block that
    // looks generated.
    const tree = treeWith({
      'openrca-1.0.md': [
        '# openrca-1.0',
        '',
        '<!-- example: openrca-9.9/order-prod/query.csv -->',
        '```csv',
        'stale',
        '```',
        '',
      ].join('\n'),
    });

    const result = run(tree);

    expect(result.status).not.toBe(0);
    expect(result.stderr).toContain("unknown example target 'openrca-9.9'");
  });

  it('refuses an example naming a path the target does not export', () => {
    // The second throw, and a different one: the target exists and the file
    // does not. This is the message that catches a renamed export.
    //
    // The assertion names the **path the gate reports**, which is the marker's
    // own reference minus the target key -- `order-prod/no-such-file.csv`, with
    // the `order-prod/` prefix kept. The first version asserted the bare
    // basename and failed, which is worth recording: the message a reader gets
    // carries the whole relative path, and a test asserting less than the
    // message says would pass a gate that reported only the file name.
    const tree = treeWith({
      'openrca-1.0.md': [
        '# openrca-1.0',
        '',
        '<!-- example: openrca-1.0/order-prod/no-such-file.csv -->',
        '```csv',
        'stale',
        '```',
        '',
      ].join('\n'),
    });

    const result = run(tree);

    expect(result.status).not.toBe(0);
    expect(result.stderr).toContain("example path 'order-prod/no-such-file.csv' not exported by openrca-1.0");
  });
});

describe('scripts/gen-examples.mjs · the field tables, and what is not checked', () => {
  it('regenerates a field table from the specification', () => {
    // The fields half. The table is rendered from `FORMAT_SPECS`, so the
    // generator is the only thing that can keep it in step with the code --
    // which is the argument P2-4 makes about every other measurable number in
    // these documents.
    const tree = treeWith({
      'openrca-1.0.md': [
        '# openrca-1.0',
        '',
        '<!-- fields: openrca-1.0/{system}/query.csv -->',
        '| Field | Type | Required | Source (IR) | Notes |',
        '| --- | --- | --- | --- | --- |',
        '| `stale` | string | yes | `x` | wrong on purpose |',
        '<!-- /fields -->',
        '',
      ].join('\n'),
    });
    expect(run(tree).status).toBe(0);

    const after = readFileSync(join(tree, 'docs', 'targets', 'openrca-1.0.md'), 'utf8');
    expect(after).not.toContain('wrong on purpose');
    // The three real fields of `{system}/query.csv`, rendered from the spec.
    expect(after).toContain('`instruction_id`');
    expect(after).toContain('`occurrence_datetime`');
    expect(after).toContain('<!-- /fields -->');
  });

  it('refuses a field marker that matches no documented file', () => {
    // The third throw. A marker is a claim that the specification documents
    // this path, so a marker whose path is absent is a spelling error that
    // would otherwise produce an empty or missing table.
    const tree = treeWith({
      'openrca-1.0.md': [
        '# openrca-1.0',
        '',
        '<!-- fields: openrca-1.0/{system}/no-such-file.csv -->',
        '<!-- /fields -->',
        '',
      ].join('\n'),
    });

    const result = run(tree);

    expect(result.status).not.toBe(0);
    expect(result.stderr).toContain('does not match any documented file');
  });

  it('has no --check path for the doc blocks, so a stale table fails nothing', () => {
    // **A gap stated as a test rather than as a comment.**
    //
    // `--check` compares `site/assets/data.js` and nothing else. The example
    // blocks and the field tables are rewritten only on a *writer* run, so a
    // tree whose `docs/targets/*.md` had drifted from the specification passes
    // `--check` cleanly. This test pins that, because the alternative is to
    // leave the gap to be discovered by someone whose doc went stale silently
    // -- which is exactly what `audit.md` finding 66 records happening to
    // three counts in one pass.
    //
    // The fixture writes the **stale data file**, not a stale doc. `--check`
    // would otherwise fail on `data.js` first and this test would be measuring
    // staleness in general rather than the doc-block gap -- which is what its
    // first run did: the writer run above had already refreshed both files, so
    // the block it then asserted as "stale" was the freshly generated one and
    // the assertion on `STALE,CONTENT,…` could not hold. To isolate the gap,
    // the payload is written first and the stale marker is installed *after*
    // it, so `data.js` is current and only the doc disagrees.
    const tree = treeWith();
    expect(run(tree).status).toBe(0);
    writeFileSync(join(tree, 'docs', 'targets', 'openrca-1.0.md'), exampleMarker());
    const stale = readFileSync(join(tree, 'docs', 'targets', 'openrca-1.0.md'), 'utf8');
    expect(stale).toContain('STALE,CONTENT,FROM,A,PREVIOUS,RUN');

    const result = run(tree, ['--check']);

    // Green, on a tree whose doc block is plainly wrong.
    expect(result.status).toBe(0);
    expect(result.stdout).toContain('examples data is up to date');
    // And the stale text is still there, which is what makes the pass a gap
    // rather than a proof: `--check` never read the file.
    expect(readFileSync(join(tree, 'docs', 'targets', 'openrca-1.0.md'), 'utf8')).toBe(stale);
  });

  it('leaves a document with no markers untouched', () => {
    // The negative control for the rewriter. A `replace` that ran over every
    // line would reformat documents it has no business touching, and in a
    // repository of hand-written prose that is the expensive direction.
    const body = '# openrca-1.0\n\nProse with no markers at all.\n\n| a | b |\n| --- | --- |\n';
    const tree = treeWith({ 'openrca-1.0.md': body });
    expect(run(tree).status).toBe(0);

    expect(readFileSync(join(tree, 'docs', 'targets', 'openrca-1.0.md'), 'utf8')).toBe(body);
  });
});
