/**
 * Intermediate Representation (IR) type definitions.
 *
 * The IR is deliberately layered:
 *   Layer 1  TelemetrySignal  - a single observed fact
 *   Layer 2  EntityGraph      - the topology every reference must resolve against
 *   Layer 3  FaultCase        - one failure plus its ground truth
 *   Layer 4  QualityGateReport- the evidence that proves the case is usable
 *
 * Two invariants are enforced everywhere, not by convention:
 *   1. Every entity reference MUST resolve against the EntityGraph.
 *   2. Fields whose provenance is `inferred` MUST NOT be used for ground-truth
 *      key fields (root cause entity, injection time, causal chain).
 */

/** Current IR contract version. Bump on any breaking change. */
export const IR_VERSION = '2.0';

/**
 * Observability signal kinds supported by the IR.
 *
 * The type is derived from the tuple so the values and the type cannot
 * disagree, and every consumer that needs the list at runtime -- the coverage
 * computation, the HTML report's modality rows, and the CLI's `--signal-kind`
 * set -- reads this rather than restating it. Two consumers previously kept
 * their own copy under a different name, and dropping a member from the
 * report's copy silently removed a modality row from the rendered evidence.
 */
export const SIGNAL_KINDS = ['metric', 'log', 'trace', 'event', 'alert', 'profile'] as const;

export type SignalKind = (typeof SIGNAL_KINDS)[number];

/**
 * Answer the question "does this string belong to that vocabulary?" without
 * the compiler being told to trust a cast.
 *
 * `readonly ['A', 'B'].includes(someString)` does not compile -- a tuple's
 * `includes` only accepts its own members, which is exactly the guarantee worth
 * having and exactly the reason the six consumers of these vocabularies used to
 * restate each tuple as a `readonly string[]` instead. This one helper is what
 * lets them drop the restatement: the answer is derived from the tuple, and the
 * narrows to the tuple's member type.
 */
export function isVocabularyMember<V extends string>(
  vocabulary: readonly V[],
  value: string,
): value is V {
  return vocabulary.some((candidate) => candidate === value);
}

/**
 * `LogPayload.severityText`, declared once.
 *
 * The union used to sit inside the interface while `ingest/file.ts` kept a
 * hand-written `readonly string[]` beside it. Adding a member to the copy was
 * silent and removing one was silent, because `string` contains everything and
 * the copy is what actually decided which severities reach the IR.
 */
export const LOG_SEVERITIES = ['TRACE', 'DEBUG', 'INFO', 'WARN', 'ERROR', 'FATAL'] as const;

/** A log severity. Derived from `LOG_SEVERITIES`. */
export type LogSeverity = (typeof LOG_SEVERITIES)[number];

/**
 * `TracePayload.status`, declared once, for the same reason. `UNSET` is a real
 * member of the vocabulary -- a span with no status -- not a default applied
 * when parsing fails.
 */
export const SPAN_STATUSES = ['OK', 'ERROR', 'UNSET'] as const;

/** A span status. Derived from `SPAN_STATUSES`. */
export type SpanStatus = (typeof SPAN_STATUSES)[number];

/** Where a field value came from. */
export type ProvenanceSource = 'direct' | 'derived' | 'inferred' | 'defaulted';

export interface FieldProvenance {
  source: ProvenanceSource;
  /** Id of the rule that produced this field. */
  ruleId?: string;
  /** Model identifier when the rule was generated by an LLM. */
  modelId?: string;
  /** Prompt version, so a generated rule stays reproducible. */
  promptVersion?: string;
  /** 0..1 confidence reported by the generator. */
  confidence?: number;
}

/**
 * `MetricPayload.semanticType`, declared once, for the same reason.
 *
 * This was an inline union in the interface, which meant no consumer could read
 * the vocabulary at runtime, and the one consumer that actually needed to --
 * the LLM rule generator, which has to tell a model which values are legal --
 * could only advertise the field name and reject the model's answer later,
 * downstream, as a schema failure on the whole record.
 */
export const METRIC_SEMANTIC_TYPES = [
  'latency', 'error_rate', 'throughput', 'saturation', 'availability', 'other',
] as const;

/** A metric semantic class. Derived from `METRIC_SEMANTIC_TYPES`. */
export type MetricSemanticType = (typeof METRIC_SEMANTIC_TYPES)[number];

export interface MetricPayload {
  kind: 'metric';
  /** Metric name, e.g. `container_cpu_usage_seconds_total`. */
  name: string;
  value: number;
  /** UCUM-style unit, e.g. `s`, `By`, `%`. */
  unit?: string;
  /** Semantic class used by downstream exporters and gates. */
  semanticType?: MetricSemanticType;
  tags?: Record<string, string>;
}

export interface LogPayload {
  kind: 'log';
  body: string;
  severityText?: LogSeverity;
  /** Drain-style template id, e.g. `L007`. */
  templateId?: string;
  /** Parameters extracted by the template, keyed by placeholder name. */
  params?: Record<string, string>;
}

export interface TracePayload {
  kind: 'trace';
  traceId: string;
  spanId: string;
  /** Absent for root spans. */
  parentSpanId?: string;
  spanName: string;
  /** Span duration in milliseconds. */
  durationMs: number;
  status?: SpanStatus;
  attributes?: Record<string, string>;
}

export interface EventPayload {
  kind: 'event';
  /** Kubernetes reason, e.g. `OOMKilled`, or a platform-specific reason code. */
  reason: string;
  message?: string;
  type?: 'Normal' | 'Warning';
  count?: number;
  /** Sub-type used for deployment / configuration changes. */
  changeType?: 'deploy' | 'config' | 'scale' | 'rollback';
  involvedObject?: { kind: string; name: string };
}

export interface AlertPayload {
  kind: 'alert';
  alertName: string;
  severity?: 'critical' | 'warning' | 'info';
  state?: 'firing' | 'resolved';
  labels?: Record<string, string>;
  annotations?: Record<string, string>;
}

export interface ProfilePayload {
  kind: 'profile';
  profileType: 'cpu' | 'heap' | 'goroutine' | 'flamegraph';
  /** Reference to the out-of-band payload; profiles never live in the main table. */
  payloadRef: string;
  samplePeriodMs?: number;
}

export type SignalPayload =
  | MetricPayload
  | LogPayload
  | TracePayload
  | EventPayload
  | AlertPayload
  | ProfilePayload;

export interface TelemetrySignal {
  irVersion: string;
  /** OpenTelemetry semantic-convention core subset. */
  resource: {
    'service.name': string;
    'service.namespace'?: string;
    'service.version'?: string;
    'k8s.pod.name'?: string;
    'k8s.node.name'?: string;
    'host.name'?: string;
    [key: string]: string | undefined;
  };
  /** Canonical UTC ISO-8601, e.g. `2026-09-06T04:05:06.000Z`. */
  timestamp: string;
  /** Offset carried by (or assumed for) the source value, in minutes east of UTC. */
  rawOffsetMinutes?: number;
  signal: SignalKind;
  payload: SignalPayload;
  /** Per-field origin tracking, keyed by dotted field path. */
  provenance?: Record<string, FieldProvenance>;
}

/**
 * Entity kinds, declared once.
 *
 * Several exporters key a `Record<EntityKind, …>` off this union, so the
 * compiler already refuses to let a member disappear. The vocabulary is now a
 * tuple rather than a bare union so that the runtime consumers -- AIOps2025's
 * `instance_type` set among them -- narrow it instead of copying it.
 */
export const ENTITY_KINDS = [
  'service',
  'pod',
  'node',
  'container',
  'db',
  'mq',
  'host',
  'cluster',
  'external',
] as const;

/** An entity kind. Derived from `ENTITY_KINDS`. */
export type EntityKind = (typeof ENTITY_KINDS)[number];

export interface Entity {
  /** Globally unique id, formatted `${kind}:${namespace}/${name}`. */
  entityId: string;
  kind: EntityKind;
  name: string;
  namespace?: string;
  /** Names used for the same entity in APM / Kubernetes / CMDB. */
  aliases: string[];
  attributes?: Record<string, string>;
}

export type EntityRelation = 'contains' | 'hosts' | 'calls' | 'same_as';

export interface EntityEdge {
  from: string;
  to: string;
  relation: EntityRelation;
  attributes?: Record<string, string>;
}

export interface EntityGraph {
  entities: Entity[];
  edges: EntityEdge[];
}

/**
 * Fault categories, declared once and in the order they are published in
 * `docs/data-model.md`.
 *
 * `unknown` is a member of the contract, not a fallback applied when inference
 * fails; the inference table returns it explicitly for a type it cannot place.
 */
export const FAULT_CATEGORIES = [
  'resource',
  'network',
  'runtime',
  'middleware',
  'code',
  'config',
  'dependency',
  'unknown',
] as const;

/** A fault category. Derived from `FAULT_CATEGORIES`. */
export type FaultCategory = (typeof FAULT_CATEGORIES)[number];

export type Comparator = '>' | '>=' | '<' | '<=' | '==' | '!=' | 'contains' | 'matches';

export interface EvidenceCheckpoint {
  checkpointId: string;
  /** Must resolve against the EntityGraph. */
  entityRef: string;
  /** Optional pointer to the concrete metric / log / trace. */
  signalRef?: string;
  comparator: Comparator;
  value: number | string;
  /** UCUM-style unit. Required whenever `value` is numeric. */
  unit?: string;
  description: string;
}

export interface CausalStep {
  step: number;
  fromEntityId: string;
  toEntityId: string;
  mechanism: string;
  /** References to `EvidenceCheckpoint.checkpointId`. */
  evidenceRefs: string[];
}

export interface RootCauseIndicator {
  type: 'metric' | 'log' | 'trace';
  ref: string;
  description: string;
}

export interface GroundTruth {
  /** Must resolve against the EntityGraph. */
  rootCauseEntityId: string;
  rootCauseComponent: string;
  rootCauseReason: string;
  rootCauseIndicators?: RootCauseIndicator[];
  causalChain?: CausalStep[];
  evidenceCheckpoints?: EvidenceCheckpoint[];
  remediation?: Array<{ step: number; action: string; target: string }>;
}

export interface FaultCase {
  caseId: string;
  system: string;
  environment: {
    system: string;
    version?: string;
    deployRef?: string;
    reproducerRef?: string;
    checksums?: Record<string, string>;
  };
  /** Canonical UTC ISO-8601 injection / onset time. */
  injectTime: string;
  window: { start: string; end: string };
  fault: {
    type: string;
    category: FaultCategory;
    injectionMethod?: 'chaos-mesh' | 'litmus' | 'chaosblade' | 'historical' | 'manual';
    parameters?: Record<string, unknown>;
  };
  groundTruth: GroundTruth;
  /** Natural-language task description required by OpenRCA-style benchmarks. */
  query?: string;
  difficulty?: 'L1' | 'L2' | 'L3' | 'L4';
  quality?: QualityGateReport;
  /** True when the answer key is stored physically separate from the task. */
  answerKeyIsolated?: boolean;
}

export type GateId = 'G1' | 'G2' | 'G3' | 'G4' | 'G5';

export type GateStatus = 'passed' | 'quarantined' | 'failed';

export interface GateViolation {
  code: string;
  message: string;
  /** Dotted path of the offending field, when applicable. */
  fieldPath?: string;
}

export interface GateResult {
  gateId: GateId;
  status: GateStatus;
  violations: GateViolation[];
}

export interface QualityGateReport {
  caseId: string;
  irVersion: string;
  gateRunId: string;
  runAt: string;
  results: GateResult[];
  finalStatus: 'admitted' | 'quarantined' | 'rejected';
  /** True only when the mutation suite proved the gates themselves still work. */
  mutationTestPassed?: boolean;
}

/** A complete bundle: signals, topology, cases. */
export interface IrBundle {
  irVersion: string;
  graph: EntityGraph;
  cases: FaultCase[];
  /** Signals grouped by case id. */
  signals: Record<string, TelemetrySignal[]>;
}

/**
 * One assertion inside a fault-validity report.
 *
 * Same shape as `ScoreCheck` in `score/score.ts` -- `{id, passed, detail}` with a
 * flat array and an aggregate verdict -- because the two reports answer the same
 * kind of question ("is this artifact what it claims to be") and a reader should
 * not have to learn two formats for it.
 */
export interface ValidityCheck {
  id: string;
  passed: boolean;
  detail: string;
}

/**
 * The verdict on whether a declared fault actually happened.
 *
 * Three values, and `unverifiable` is not a softer `invalid`. When the telemetry
 * carries nothing the fault's mechanism could have moved, the honest answer is
 * that the evidence cannot decide -- not that the fault failed. Collapsing the two
 * would turn an absence of data into a finding, which is the overclaim that
 * fault-validity verification exists to prevent.
 */
export type FaultValidityVerdict = 'valid' | 'invalid' | 'unverifiable';

/** The report `verifyFaultValidity` returns. */
export interface FaultValidityReport {
  caseId: string;
  verdict: FaultValidityVerdict;
  checks: ValidityCheck[];
  /** The entity the case names as root cause, and the service it resolved to. */
  target: { entityId: string | null; service: string | null };
  /** What the telemetry actually showed, as opposed to what was declared. */
  observed: { affectedSeries: string[]; onsetOffsetSeconds: number | null };
}
