/**
 * Intermediate Representation (IR) type definitions.
 *
 * The IR is deliberately layered:
 *   Layer 1  TelemetrySignal  - a single observed fact
 *   Layer 2  EntityGraph      - the topology every reference must resolve against
 *   Layer 3  FaultCase        - one failure plus its ground truth
 *   Layer 4  QualityGateReport- the evidence that proves the case is usable
 *
 * Two invariants are enforced everywhere, not by convention:
 *   1. Every entity reference MUST resolve against the EntityGraph.
 *   2. Fields whose provenance is `inferred` MUST NOT be used for ground-truth
 *      key fields (root cause entity, injection time, causal chain).
 */

/** Current IR contract version. Bump on any breaking change. */
export const IR_VERSION = '2.0';

/** Observability signal kinds supported by the IR. */
export type SignalKind = 'metric' | 'log' | 'trace' | 'event' | 'alert' | 'profile';

/** Where a field value came from. */
export type ProvenanceSource = 'direct' | 'derived' | 'inferred' | 'defaulted';

export interface FieldProvenance {
  source: ProvenanceSource;
  /** Id of the rule that produced this field. */
  ruleId?: string;
  /** Model identifier when the rule was generated by an LLM. */
  modelId?: string;
  /** Prompt version, so a generated rule stays reproducible. */
  promptVersion?: string;
  /** 0..1 confidence reported by the generator. */
  confidence?: number;
}

export interface MetricPayload {
  kind: 'metric';
  /** Metric name, e.g. `container_cpu_usage_seconds_total`. */
  name: string;
  value: number;
  /** UCUM-style unit, e.g. `s`, `By`, `%`. */
  unit?: string;
  /** Semantic class used by downstream exporters and gates. */
  semanticType?: 'latency' | 'error_rate' | 'throughput' | 'saturation' | 'availability' | 'other';
  tags?: Record<string, string>;
}

export interface LogPayload {
  kind: 'log';
  body: string;
  severityText?: 'TRACE' | 'DEBUG' | 'INFO' | 'WARN' | 'ERROR' | 'FATAL';
  /** Drain-style template id, e.g. `L007`. */
  templateId?: string;
  /** Parameters extracted by the template, keyed by placeholder name. */
  params?: Record<string, string>;
}

export interface TracePayload {
  kind: 'trace';
  traceId: string;
  spanId: string;
  /** Absent for root spans. */
  parentSpanId?: string;
  spanName: string;
  /** Span duration in milliseconds. */
  durationMs: number;
  status?: 'OK' | 'ERROR' | 'UNSET';
  attributes?: Record<string, string>;
}

export interface EventPayload {
  kind: 'event';
  /** Kubernetes reason, e.g. `OOMKilled`, or a platform-specific reason code. */
  reason: string;
  message?: string;
  type?: 'Normal' | 'Warning';
  count?: number;
  /** Sub-type used for deployment / configuration changes. */
  changeType?: 'deploy' | 'config' | 'scale' | 'rollback';
  involvedObject?: { kind: string; name: string };
}

export interface AlertPayload {
  kind: 'alert';
  alertName: string;
  severity?: 'critical' | 'warning' | 'info';
  state?: 'firing' | 'resolved';
  labels?: Record<string, string>;
  annotations?: Record<string, string>;
}

export interface ProfilePayload {
  kind: 'profile';
  profileType: 'cpu' | 'heap' | 'goroutine' | 'flamegraph';
  /** Reference to the out-of-band payload; profiles never live in the main table. */
  payloadRef: string;
  samplePeriodMs?: number;
}

export type SignalPayload =
  | MetricPayload
  | LogPayload
  | TracePayload
  | EventPayload
  | AlertPayload
  | ProfilePayload;

export interface TelemetrySignal {
  irVersion: string;
  /** OpenTelemetry semantic-convention core subset. */
  resource: {
    'service.name': string;
    'service.namespace'?: string;
    'service.version'?: string;
    'k8s.pod.name'?: string;
    'k8s.node.name'?: string;
    'host.name'?: string;
    [key: string]: string | undefined;
  };
  /** Canonical UTC ISO-8601, e.g. `2026-09-06T04:05:06.000Z`. */
  timestamp: string;
  /** Offset carried by (or assumed for) the source value, in minutes east of UTC. */
  rawOffsetMinutes?: number;
  signal: SignalKind;
  payload: SignalPayload;
  /** Per-field origin tracking, keyed by dotted field path. */
  provenance?: Record<string, FieldProvenance>;
}

export type EntityKind =
  | 'service'
  | 'pod'
  | 'node'
  | 'container'
  | 'db'
  | 'mq'
  | 'host'
  | 'cluster'
  | 'external';

export interface Entity {
  /** Globally unique id, formatted `${kind}:${namespace}/${name}`. */
  entityId: string;
  kind: EntityKind;
  name: string;
  namespace?: string;
  /** Names used for the same entity in APM / Kubernetes / CMDB. */
  aliases: string[];
  attributes?: Record<string, string>;
}

export type EntityRelation = 'contains' | 'hosts' | 'calls' | 'same_as';

export interface EntityEdge {
  from: string;
  to: string;
  relation: EntityRelation;
  attributes?: Record<string, string>;
}

export interface EntityGraph {
  entities: Entity[];
  edges: EntityEdge[];
}

export type FaultCategory =
  | 'resource'
  | 'network'
  | 'runtime'
  | 'middleware'
  | 'code'
  | 'config'
  | 'dependency'
  | 'unknown';

export type Comparator = '>' | '>=' | '<' | '<=' | '==' | '!=' | 'contains' | 'matches';

export interface EvidenceCheckpoint {
  checkpointId: string;
  /** Must resolve against the EntityGraph. */
  entityRef: string;
  /** Optional pointer to the concrete metric / log / trace. */
  signalRef?: string;
  comparator: Comparator;
  value: number | string;
  /** UCUM-style unit. Required whenever `value` is numeric. */
  unit?: string;
  description: string;
}

export interface CausalStep {
  step: number;
  fromEntityId: string;
  toEntityId: string;
  mechanism: string;
  /** References to `EvidenceCheckpoint.checkpointId`. */
  evidenceRefs: string[];
}

export interface RootCauseIndicator {
  type: 'metric' | 'log' | 'trace';
  ref: string;
  description: string;
}

export interface GroundTruth {
  /** Must resolve against the EntityGraph. */
  rootCauseEntityId: string;
  rootCauseComponent: string;
  rootCauseReason: string;
  rootCauseIndicators?: RootCauseIndicator[];
  causalChain?: CausalStep[];
  evidenceCheckpoints?: EvidenceCheckpoint[];
  remediation?: Array<{ step: number; action: string; target: string }>;
}

export interface FaultCase {
  caseId: string;
  system: string;
  environment: {
    system: string;
    version?: string;
    deployRef?: string;
    reproducerRef?: string;
    checksums?: Record<string, string>;
  };
  /** Canonical UTC ISO-8601 injection / onset time. */
  injectTime: string;
  window: { start: string; end: string };
  fault: {
    type: string;
    category: FaultCategory;
    injectionMethod?: 'chaos-mesh' | 'litmus' | 'chaosblade' | 'historical' | 'manual';
    parameters?: Record<string, unknown>;
  };
  groundTruth: GroundTruth;
  /** Natural-language task description required by OpenRCA-style benchmarks. */
  query?: string;
  difficulty?: 'L1' | 'L2' | 'L3' | 'L4';
  quality?: QualityGateReport;
  /** True when the answer key is stored physically separate from the task. */
  answerKeyIsolated?: boolean;
}

export type GateId = 'G1' | 'G2' | 'G3' | 'G4' | 'G5';

export type GateStatus = 'passed' | 'quarantined' | 'failed';

export interface GateViolation {
  code: string;
  message: string;
  /** Dotted path of the offending field, when applicable. */
  fieldPath?: string;
}

export interface GateResult {
  gateId: GateId;
  status: GateStatus;
  violations: GateViolation[];
}

export interface QualityGateReport {
  caseId: string;
  irVersion: string;
  gateRunId: string;
  runAt: string;
  results: GateResult[];
  finalStatus: 'admitted' | 'quarantined' | 'rejected';
  /** True only when the mutation suite proved the gates themselves still work. */
  mutationTestPassed?: boolean;
}

/** A complete bundle: signals, topology, cases. */
export interface IrBundle {
  irVersion: string;
  graph: EntityGraph;
  cases: FaultCase[];
  /** Signals grouped by case id. */
  signals: Record<string, TelemetrySignal[]>;
}
